# Generated by Django 3.1.2 on 2020-10-31 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked',
            new_name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
